# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'EnTurma' do
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
pod "PageMenu"
pod "Alamofire", '~> 1.2'
end

target 'EnTurmaTests' do

end

