# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'EnTurma' do
use_frameworks!
pod "AFNetworking", "~> 2.0"
pod "PageMenu"

end

target 'EnTurmaTests' do

end

